server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 7mb
      max-request-size: 70mb
      enabled: true
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/xydc
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false #配置缓存清空，不用重启服务区也能看到静态资源的变化
  devtools:
    restart:
      enabled: true #开启热部署

#配置mapper配置的路径，天坑，classpath不是属性，而是值
mybatis:
  mapper-locations: com/yisn/modules/mapper/**/*.xml #mapping/*.xml ,com/yisn/modules/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰转换数据库字段为academy_name 对应实体类的属性为 private String academyName
file:
  kitchen: /kitchen
  product: /product
  licenses: /licenses
  store: /store

